[tool.poetry]
name = "paper-bridge"
version = "0.1.0"
description = "A project that delivers daily AI/ML paper summaries"
authors = ["Jonas Kim <youngmki@amazon.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
arxiv = "^2.1.3"
jupyter-black = "^0.4.0"
llama-index-core = "0.12.6"
llama-index-llms-bedrock = "^0.3.3"
numpy = "1.24.3"
pymupdf = "^1.25.2"
spacy = "^3.0.0"
graphrag-toolkit = {url = "https://github.com/awslabs/graphrag-toolkit/archive/refs/tags/v1.1.3.zip"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
