resources:
  project_name: paper-bridge
  stage: dev
  default_region_name: us-west-2
  bedrock_region_name: us-west-2
  s3_bucket_name: sagemaker-us-west-2-998601677581
  s3_prefix: paper-bridge-dev

summarization:
  papers_per_day: 1
  days_to_fetch: 1
  min_upvotes: 10
  parse_pdf: False
  figure_analysis_model_id: anthropic.claude-3-haiku-20240307-v1:0
  paper_summarization_model_id: anthropic.claude-3-7-sonnet-20250219-v1:0

retrieval:
  output_format: slack
  traversal_based_or_semantic_guided: traversal_based
  set_subretriever: False
  use_reranking_beam_search: False
  use_post_processors: False
  use_gpu_reranker: False
  gpu_id: 0
  use_diversity: False
  use_enhancement: False
  retrieval_summarization_model_id: anthropic.claude-3-7-sonnet-20250219-v1:0
